### ISSUE TITLE
Không click được và Icon requests khi tìm kiếm đã xong 

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#10]
Không click được và Icon equests khi tìm kiếm đã xong 
![9](https://cloud.githubusercontent.com/assets/19528063/17325298/0863db16-58d5-11e6-871b-266a909d266a.PNG)

**Comment by giangdhwhtbr** [comment]
Long có thể để cái trang search sang component khác, không chung vs request để tránh trường hợp này mà vẫn giữ được thế mạnh của routeLink

**Comment by namnvse02297** [comment]
Bug đã fix
