### ISSUE TITLE
Bug Category : hiện tri thức con phía trên tri thức con

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#101]
B1 Làm như trong hình 
![3](https://cloud.githubusercontent.com/assets/19528063/18009828/b76e49d0-6b62-11e6-8f18-412bc353ec29.PNG)
Bug : hiện tri thức con phía trên tri thức con (Trong hình)
![4](https://cloud.githubusercontent.com/assets/19528063/18009852/d6bbcdd0-6b62-11e6-8d62-d1f6fa075af0.PNG)

**Comment by AnhNQSE03216** [comment]
là sao e k hiểu

**Comment by namnvse02297** [comment]
chú làm theo như trong anh đi
