### ISSUE TITLE
Bug Phần quản lý tri thức : khi một tri thức  con chuyển từ trạng thái deactive sang active

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#17]
B1 : Vào trang quản lý của admin 
B2 : Vào quản lý tri thức
B3 : click vào nút active của một thằng con khi thằng cha ý đang ở trạng thái deactive
![12](https://cloud.githubusercontent.com/assets/19528063/17390142/7d259bf0-5a34-11e6-8a81-3b2de8f990ba.PNG)
Bug
Nó hiện ra tất cả thằng con và ngang hàng với thằng cha
![14](https://cloud.githubusercontent.com/assets/19528063/17390525/0b0c5c62-5a38-11e6-990b-131cfccf1553.PNG)

**Comment by AnhNQSE03216** [comment]
Đã fix những lỗi lquan đến active với deactive nhé

**Comment by namnvse02297** [comment]
bug đã fix Ngày test 5/8/2016
