### ISSUE TITLE
Bug Phần quản lý tri thức : Số thứ tự 

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#24]
B1 : vào trang quản lý của admin
B2 : vào phần quản lý tri thức
Issues
Không hiện số thứ tự thì bỏ luôn cột số thứ tự đi 
![7](https://cloud.githubusercontent.com/assets/19528063/17412311/48399b9a-5aa6-11e6-805f-32217c4d40bd.png)

**Comment by giangdhwhtbr** [comment]
@AnhNQSE03216  Số thứ tự vẫn phải có, hôm trước anh bảo rồi, không phải gặp lỗi thì bỏ nó đi ko sửa như thế
