### ISSUE TITLE
Bug Trang quản lý của Admin : Phần quản lý tri thức : Quản lý tri thức con không hợp lý

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#25]
B1 : Vào trang quản lý của admin
B2 : show toàn bộ tri thức con trong một tri thức cha
B3 : active or deactive của tri thức con
![8](https://cloud.githubusercontent.com/assets/19528063/17424805/96dceb1c-5af1-11e6-9d8b-fc8afac790cd.png)
Issues 
Không thể active or deactive nhiều tri thức con trong của một tri thức con cùng một lúc

**Comment by giangdhwhtbr** [comment]
Đúng rồi, chỗ này phải làm sao để nó có thể deactive nhiều cái một lần chứ không phải cứ deactive 1 cái nó lại load lại trang rất bất tiện, Chú có thể nghiên cứu làm cái checkbox và tạo nút để nó update 1 loạt. Cái này liên quan đến nghiệp vụ quản lí cơ bản nên phải làm.
