### ISSUE TITLE
Bug Trang quản lý của Admin : Phần quản lý tri thức : Lỗi active và deactive

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#26]
Bug khi deactive tri thức cha mà tri thức con vẫn được active
![10](https://cloud.githubusercontent.com/assets/19528063/17424997/322afc34-5af3-11e6-98fc-9def50358331.png)

**Comment by giangdhwhtbr** [comment]
@AnhNQSE03216  đây là code mới rồi đấy nhé, kiểm tra và sửa đi

**Comment by AnhNQSE03216** [comment]
Lỗi này hqua e nói Nam rồi cái này là do tải lên server nhiều request nên
sẽ gây hiệu ứng lag. Ấn deactive cha có nhiều con thì nên đợi 1 tí rồi ktra
lại

**Comment by giangdhwhtbr** [comment]
@AnhNQSE03216  sao lại là nhiều request lên server. Khi deactive cha thì em chỉ đúng 1 request được gửi lên mang thông điệp là có 1 knowledge cha bị deactive sau đó mọi chuyện xử lí là ở server em trả lại dữ liệu cũng chỉ là data thể hiện là thằng cha và con nó bị deactive rồi đổi trạng thái hiển thị.
 Đúng 1 request và 1 response ở đâu mà nhiều? Khi mà tester báo lỗi thì nhiệm vụ của chú là kiểm tra và khắc phục, chứ không phải cãi rồi mặc kệ. Đến lúc bảo vệ các thầy nhìn vào kết quả chứ ko cần sự giải trình. Hiểu ko????

**Comment by AnhNQSE03216** [comment]
k phải e cãi. a deactive cha nhé thì nó sẽ tìm xem bên trong cha có những đứa nào là con rồi sẽ gửi lần lượt các request sửa lên. cha nào càng nhiều con thì lượng request nó gửi lên sẽ càng nhiều chứ đâu phải chỉ có 1 request đâu.

**Comment by giangdhwhtbr** [comment]
sao lại gửi lần lượt? ko đóng thành một cục mà gửi lên được à?

**Comment by AnhNQSE03216** [comment]
Đóng gói kiểu gì đc a vì nó muốn sửa thì thì vẫn phải truy cập vào đường
link với id của nó nên vẫn tính là 1 request rồi

**Comment by giangdhwhtbr** [comment]
@AnhNQSE03216  @ducduongtmb  @kiddyhpzx94 

Sai Model dẫn đến cái hàm viết tệ như thế này ở Client

changeKnowledgeStatus(knowledge):void {
      this._knowledgeService
          .changeKnowledgeStatus(knowledge)
          .subscribe((knowledge) => {
          });
          if(knowledge.hasOwnProperty("subCategory")){
            for(var i = 0 ;i < knowledge["subCategory"].length;i++){
              if(knowledge["subCategory"][i].status==knowledge.status){
                this._knowledgeService
                    .changeKnowledgeStatus(knowledge["subCategory"][i])
                    .subscribe((knowledge) => {})
              }
            }
          }
        this.sort();
    }

**Comment by giangdhwhtbr** [comment]
Cách giải quyết tạm thời, Quang Anh lo nốt

`static changeKnowledgeStatus(req, res){
      var currentDate = new Date();
      if(req.params && req.params.id) {
          KnowledgeDAO.getKnowledgeById(req.params.id)
            .then(parent => {
              // ở đây đã tìm ra thằng cha 
              // update cha 
              parent.status = !parent.status;
              var parentUpdate = KnowledgeDAO.UpdateStatus(parent){
                parent => {return true},
                error  => {return false} 
              }
              var childrenUpdate = KnowledgeDAO.getKnowledgeByParentId(parent.id){
                //tim ra thang con
                child => {
                  child.status = !child.status;
                  return KnowledgeDAO.UpdateStatus(child){
                    child => {return true},
                    error => {return false}
                  }                  
                }
              }
              if(!childrenUpdate){
                res.status(200).json({
                  message: 'parent update success, no children',
                  status: parent.status
                })
              }else {
                res.status(200).json({
                  message: 'parent and children update success',
                  status: parent.status
                })
              }
            })
            .catch(error => res.status(400).json(error));
      }else{
        res.status(404).json({
          "message"    :   "No knowledge id in templates"
        });
      }
    }`
