### ISSUE TITLE
Bug Trang quản lý của Admin : Phần quản lý tri thức : Lỗi active và deactive

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#27]
B1 Vào deactive của một trí thức còn
![11](https://cloud.githubusercontent.com/assets/19528063/17425071/a62c7176-5af3-11e6-8065-67239694312e.png)

B2 deactive tri  thức cha của tri thức con ý
![12](https://cloud.githubusercontent.com/assets/19528063/17425080/ba9d995a-5af3-11e6-863b-4e3079e10d63.png)
B3 active tri thức cha ý
Issues:
Toàn bộ tri thức con đều được active
![13](https://cloud.githubusercontent.com/assets/19528063/17425108/eeef2d0e-5af3-11e6-8c47-e1d2a11a13af.png)

**Comment by AnhNQSE03216** [comment]
active tri thức cha thì toàn bộ con được active là hợp lý rồi còn gì nữa a ?

**Comment by namnvse02297** [comment]
active tri thức cha thì tri thức con lúc trước như thế nào thì hiện nguyên như thế

**Comment by giangdhwhtbr** [comment]
Lỗi này đặt label là enhancement, sau này có thời gian thì sửa sau
