### ISSUE TITLE
Bug Trang quản lý của Admin : Phần quản user : Tao User mới

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#28]
user gồm các ký tự đặc biệt vẫn tạo được
![14](https://cloud.githubusercontent.com/assets/19528063/17425378/dcbc2c60-5af6-11e6-9007-ee2ebdd78839.png)

**Comment by namnvse02297** [comment]
bug đã fic

**Comment by giangdhwhtbr** [comment]
Lý do: chưa giới hạn kí tự trong tên đăng nhập
=> sửa lại: giới hạn tên đăng nhập chỉ bao gồm kí tự alphabet và số
