### ISSUE TITLE
Bug :Không hiển thị email trong trang cá nhân của user

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#31]
Vào trang cá nhân của một user Email không được hiển thị ra :
![1](https://cloud.githubusercontent.com/assets/19528063/17432660/9a067586-5b2a-11e6-9dea-8cb9fe4a09f4.png)

**Comment by kiddyhpzx94** [comment]
Nó ko có email thì nó không hiển thị, để e sửa thành nếu không có email thì bỏ dòng email đi

**Comment by giangdhwhtbr** [comment]
@kiddyhpzx94 làm gì có thằng user nào ko có email hả em? email là trường required mà

**Comment by kiddyhpzx94** [comment]
thế để xem lại

**Comment by kiddyhpzx94** [comment]
chỗ dao anh Giang select trừ email đi lên nó ko lôi email ra đc

**Comment by giangdhwhtbr** [comment]
@kiddyhpzx94 thế thì phải viết hàm select khác. vì hàm đó a select để phục vụ hàm update user. Chú mà sửa ở đấy là chết đấy

**Comment by namnvse02297** [comment]
bug đã fix
