### ISSUE TITLE
Bug Phần article : khi close một article

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#37]
Khi admin close một article nên có thông báo cho người tạo article 
![2](https://cloud.githubusercontent.com/assets/19528063/17444144/a376833e-5b68-11e6-9f1f-d728688b8c61.png)

**Comment by kiddyhpzx94** [comment]
làm local mai up

**Comment by kiddyhpzx94** [comment]
fix rồi anh Nam check đi
