### ISSUE TITLE
Bug Phần article : khi report một  article

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#38]
Khi người dùng click vào một report của một article bất ký không hiện trang report mà nó trở về trang home
![1](https://cloud.githubusercontent.com/assets/19528063/17444226/0d3d6d96-5b69-11e6-9373-b31a53e23d5b.png)

**Comment by giangdhwhtbr** [comment]
Ở đây a nghĩ nên ở nguyên đó ko navigate đi đâu cả vì article này vẫn chưa bị deactive vẫn hợp lệ cho đến khi bị admin deactive.

**Comment by kiddyhpzx94** [comment]
cái này chưa làm

**Comment by namnvse02297** [comment]
Bug đã fix
