### ISSUE TITLE
Đăng ký bị sai

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#4]
![1](https://cloud.githubusercontent.com/assets/19528063/17324579/6a3e78c2-58d1-11e6-87fb-75c971a1d98b.PNG)
Khi chưa nhập gì đã hiển  thị lỗi "Sai mật khẩu xác nhận"

**Comment by ducduongtmb** [comment]
Nam Test lại xem bug giải quyết đc chưa ?

**Comment by namnvse02297** [comment]
Bug đã fic
