### ISSUE TITLE
Bug trang request : Không cần báo cáo vi phạm của chính mình tạo ra !

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#40]
![4](https://cloud.githubusercontent.com/assets/19528063/17457505/6dba6136-5c24-11e6-921d-793c7e4349bd.png)

**Comment by kiddyhpzx94** [comment]
nếu role là admin vẫn hiện chữ báo cáo vì nó có tất cả các quyền, nếu user mình thường thì ko báo cáo đc cái do mình tạo ra

**Comment by namnvse02297** [comment]
bug đã fix
