### ISSUE TITLE
Bug trang request : Khi tạo mới một request

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#41]
Tạo mới một request đến chỗ chọn lĩnh vực thì không thể chọn được tri thức cha
Mong muốn : 
Vẫn có thể chọn được tri thức cha

**Comment by kiddyhpzx94** [comment]
cái này em cố tình cho chọn tri thức cha, vì muốn nó phân loại rõ ràng hơn, nó chọn tri thức con là đã mặc định chọn tri thức cha rồi, tìm cha vẫn ra con
