### ISSUE TITLE
Bug trang requests : Bug GUI

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#45]
B1 Tìm kiếm một nội dung không khả dụng VD""2414141531633626"
Mong muốn 
Hiện  dòng chữ nhỏ ở dưới khung tìm kiếm là"Không có yêu cầu nào được tìm thấy" 
vẫn hiện all requests ở dưới
Hiện thì như bây giờ nhìn trống trải quá
![8](https://cloud.githubusercontent.com/assets/19528063/17457849/7f8d6788-5c2d-11e6-8bc7-b49b3f64269c.png)

**Comment by kiddyhpzx94** [comment]
ko tìm kiếm được request ko lên hiện list all request vì thế dễ nhầm lẫn

**Comment by kiddyhpzx94** [comment]
E sửa thêm cái nút quay lại với thêm dòng vào cho nó đỡ trống
