### ISSUE TITLE
Bug Phân Thêm bạn : Bug Khi chấp nhận một yêu cầu kết bạn của một user khác 

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#46]
Khi một user gửi lới mời kết bạn 
B1 Click vào Chấp nhận 
Bug
Ở cột Frend requests Vẫn còn 
![9](https://cloud.githubusercontent.com/assets/19528063/17457922/f91385aa-5c2e-11e6-8ec4-015ed881e177.png)
Bên cột Frend thì chưa cập nhật 
![10](https://cloud.githubusercontent.com/assets/19528063/17457936/1c3df952-5c2f-11e6-9fef-4e455dbd9e69.png)
Mong muốn : Bên cột Frend requests không còn , Bên cột Frend cập nhật ngay lập tức

**Comment by kiddyhpzx94** [comment]
nói chung là cái này nó ko real time :v
