### ISSUE TITLE
Icon không hợp lý ở phần requests

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#5]
Icon không hợp lý! nên cùng một loại Icon 
![2](https://cloud.githubusercontent.com/assets/19528063/17324714/f960ea44-58d1-11e6-9ed4-5610538c1c2b.PNG)
![3](https://cloud.githubusercontent.com/assets/19528063/17324713/f95d64f0-58d1-11e6-8259-26fa29b9a76e.PNG)

**Comment by kiddyhpzx94** [comment]
cái này đội giao diện làm lại :v:
