### ISSUE TITLE
Bug Phần requests : Khi click nhiều lần vào button theo dõi của một requests bất khì 

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#51]
![18](https://cloud.githubusercontent.com/assets/19528063/17458235/b3c9299e-5c35-11e6-962d-50f00d01634a.png)

**Comment by namnvse02297** [comment]
Vẫn bị chưa fix

**Comment by kiddyhpzx94** [comment]
anh chụp ảnh lại cho em

**Comment by namnvse02297** [comment]
![9](https://cloud.githubusercontent.com/assets/19528063/17898528/50b8696e-6982-11e6-88db-1bc6a033b5fd.PNG)
Đây anh của chú đây

**Comment by kiddyhpzx94** [comment]
ok fix rồi mai up lên server
