### ISSUE TITLE
Bug : khi admin edit một requests

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#52]
B1 Đăng nhập tài khoản admin
B2 Click edit một requests bất kì của một user thường 
Bug 
![19](https://cloud.githubusercontent.com/assets/19528063/17458281/e3262c40-5c36-11e6-812c-ee93403b3f8a.png)

**Comment by AnhNQSE03216** [comment]
e thấy cái này làm k phải là bug mà hợp lý rồi. admin chỉ có quyền deactive hoặc cảnh báo để user sửa chứ không đc sửa bài của người ta.
