### ISSUE TITLE
Bug trang request : Khi một user edit requests của chính mình 

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#53]
B1 Vào click vào button edit một requests của chính mình tạo ra 
Bug 
Nó hiện rất nhanh ra một trang mới có dòng chữ "bạn không có quyền chỉnh sửa bài viết này " (Hiện nhanh quá không chụp được ảnh ) xong đó mới hiện form edit

**Comment by kiddyhpzx94** [comment]
fix ở local chưa up lên server

**Comment by namnvse02297** [comment]
bug đã fix
