### ISSUE TITLE
Bug Trang requests: Delete requests bị lỗi

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#56]
B1 : Vào trang requests delete một requests bất khì 
bug : 
Trang requests không còn requests đấy nữa 
![5](https://cloud.githubusercontent.com/assets/19528063/17469143/d851883c-5d58-11e6-9931-c2372bce8880.png)
Trang cá nhân thì vẫn còn tồn tại requests đấy
![6](https://cloud.githubusercontent.com/assets/19528063/17469152/ed29cd00-5d58-11e6-84c6-6d30defd2520.png)

**Comment by kiddyhpzx94** [comment]
e vừa fix rồi nhưng chưa up lên server

**Comment by namnvse02297** [comment]
bug đã fix
