### ISSUE TITLE
Bug trang request : Khi tạo mới một requests

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#57]
B1 Vào trang requests click tạo mới một requests điền đầy đủ thông tin ấn Tạo
Bug : 
Lúc tạo được requests lúc không

**Comment by giangdhwhtbr** [comment]
ko chụp evidence hả Nam?

**Comment by kiddyhpzx94** [comment]
fix ở local chưa up lên server

**Comment by namnvse02297** [comment]
bug đã fix
