### ISSUE TITLE
Bug login và logout

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#59]
B1 : Đăng nhập vào một tài khoản bất kỳ
B2 : Chuyển qua chuyển lại giữa các button trong hình
![2](https://cloud.githubusercontent.com/assets/19528063/17503127/abf42f32-5e17-11e6-94dd-1ff3594fe991.png)

Bug
Nó bị tự động logout ra

**Comment by giangdhwhtbr** [comment]
Lý do: Giới hạn thời gian tồn tại của session quá ngắn (60000 milisecond <=> 1 min)  
=> Sửa lại: thời gian tồn tại của session là 1 ngày, sau 1 ngày phải đăng nhập lại

**Comment by namnvse02297** [comment]
bug đã fic
