### ISSUE TITLE
Thứ tự tìm kiếm không hợp lý 

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#6]
Thứ tự tìm kiếm không hợp lý ! nếu nhiều requests có từ học coi như việc tìm kiếm này không hiệu quả
![4](https://cloud.githubusercontent.com/assets/19528063/17324807/4e36d20e-58d2-11e6-899f-fac8691eeab5.PNG)

**Comment by kiddyhpzx94** [comment]
đã sửa

**Comment by namnvse02297** [comment]
Bug vẫn chưa fixed được

**Comment by namnvse02297** [comment]
Bug đã fic
