### ISSUE TITLE
Phải kiểm tra nội dung tìm kiếm 

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#7]
Phải kiểm tra nội dung tìm kiếm (hiện thị lỗi "Nội dung tìm kiếm của bạn không có") 
![7](https://cloud.githubusercontent.com/assets/19528063/17324908/0cb587b6-58d3-11e6-95bb-101942a53b4c.PNG)
"Nên để về màn hình requests chứ không nên để màn hình trống trơn như trên hình"

**Comment by kiddyhpzx94** [comment]
đã sửa

**Comment by namnvse02297** [comment]
Bug đã Ok
