### ISSUE TITLE
Bug Khi tìm kiếm một request

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#76]
b1:  tìm kiếm một request bất kỳ
Bug
Tìm kiếm thành công nhưng nội dung trang request bị mất
![12](https://cloud.githubusercontent.com/assets/19528063/17540954/1741a576-5ee5-11e6-9b54-17e8bb3d5f2c.png)
![13](https://cloud.githubusercontent.com/assets/19528063/17540956/1bdc72dc-5ee5-11e6-94d2-a1d32fec172d.png)

**Comment by kiddyhpzx94** [comment]
Cái này dương làm :)
