### ISSUE TITLE
Nên tìm kiếm theo cả tiêu đề và nội dung

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#8]
Cái cần tìm kiếm và cái hiển thị ra chả liên quan gì đến nhau
![8](https://cloud.githubusercontent.com/assets/19528063/17325080/d5fb80f8-58d3-11e6-939c-006cdf80ad6f.PNG)

**Comment by ducduongtmb** [comment]
cố tình làm như vậy đấy anh . full text search .

**Comment by giangdhwhtbr** [comment]
Nam miêu tả bug nên rõ ràng hơn, mù mờ thế này không ai hiểu được

**Comment by namnvse02297** [comment]
Ở đây đang tìm kiếm theo nội dung của requests! Anh nghĩ nên tìm kiếm theo cả Tiêu đề nữa !

**Comment by kiddyhpzx94** [comment]
sửa rồi

**Comment by namnvse02297** [comment]
Bug chưa sửa @kiddyhpzx94

**Comment by namnvse02297** [comment]
Test ok Bug đã fic
