### ISSUE TITLE
Bug Trang quản lý của Admin : Phần quản lý yêu cầu : các yêu cầu đã được chấp nhận không được load ra 

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#84]
B1 Click vào quản lý yêu cầu
B2 Click vào yêu cầu đã được chấp nhận
Bug 
Các yêu cầu đã được chấp nhận không được load ra
![10](https://cloud.githubusercontent.com/assets/19528063/17561610/139f42ea-5f51-11e6-9429-53590c4f55c2.png)

**Comment by kiddyhpzx94** [comment]
Đã có cái nào đâu mà hiện
