### ISSUE TITLE
Bug Trang quản lý của Admin : Phần quản lý yêu cầu : Bug Tìm kiếm

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#85]
Bước 1 Vào quản lý yêu cầu 
Bước 2 Tìm kiếm một yêu cầu bất kỳ nào đó
Bug 
Kết quả tìm kiếm sẽ theo nội dung request 
Mong muốn Tìm kiếm theo cả nội dung và yêu cầu, giống với bug (https://github.com/giangdhwhtbr/CapstoneProjectKShare/issues/8) 
![11](https://cloud.githubusercontent.com/assets/19528063/17563684/b155ea80-5f5a-11e6-9542-7d4fb83cf9f6.png)

**Comment by kiddyhpzx94** [comment]
sẽ bỏ hiện thị trường "Nội dung" ở trang đấy

**Comment by namnvse02297** [comment]
thê thì để tìm kiếm theo tiều đề

**Comment by namnvse02297** [comment]
Giờ còn không tìm kiếm được nữa

**Comment by kiddyhpzx94** [comment]
à cái đấy đang bug :v

**Comment by kiddyhpzx94** [comment]
Quang Anh fix
