### ISSUE TITLE
cập nhật ảnh đại diện bị lỗi

### ISSUE THREAD

**Issue by namnvse02297** [giangdhwhtbr/CapstoneProjectKShare#9]
cập nhật ảnh đại diện bị lỗi
Bước 1 Đăng nhập cập nhật ảnh đại diện : ok
Bước 2 Đăng xuất ra 
Bước 3 Đăng Nhập lại và trang cá nhân 
Kết quả : ảnh đại diện vừa cập nhật bị mất
![5](https://cloud.githubusercontent.com/assets/19528063/17325180/72a2bd36-58d4-11e6-94aa-958ddbbd2861.PNG)
![6](https://cloud.githubusercontent.com/assets/19528063/17325181/72a690d2-58d4-11e6-80d1-c8199d2355d1.PNG)

**Comment by kiddyhpzx94** [comment]
đã sửa

**Comment by namnvse02297** [comment]
Bug đã fic xong
